### ISSUE TITLE
lock file mismatch + unverified commits

### ISSUE THREAD

**Issue by prabhu** [jorinvo/edn-data#21]
Hello,

I am using this package in one of my projects. I noticed a new version; however, upon checking noticed that the lock file doesn't match the release. Plus, there are some unverified commits, which aren't a problem yet.

![lock-mismatch](https://github.com/jorinvo/edn-data/assets/7842/dbb19855-3848-4015-96b4-56ac076ebefd)

![signed-commits](https://github.com/jorinvo/edn-data/assets/7842/ed18e12a-0956-4526-8560-d1888846b6b1)

Could you kindly check and make a new release with the right lock file?

**Comment by jorinvo** [comment]
Thanks for opening an issue and checking this @prabhu!
I updated the lock file and released 1.1.1
Could you check if 1.1.1 looks good for you?

**Comment by jorinvo** [comment]
I am not sure I can do anything about the unverified commits now after the fact.

**Comment by prabhu** [comment]
Thank you so much for your help. 1.1.1 is looking good!
